workflow

diff --git a/.github/workflows/update-files-on-release.yml b/.github/workflows/update-files-on-release.yml
--- a/.github/workflows/update-files-on-release.yml
+++ b/.github/workflows/update-files-on-release.yml
@@ -31,20 +31,22 @@ jobs:
           new_version=$(cat version.txt)
           echo "Release version $new_version on $(date +%d.%m.%Y)" >> release_notes.txt
 
+      - name: Add SSH key
+        uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
       - name: Commit and push changes
         env:
-          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
-          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
+         GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
         run: |
-          git config --global user.name "androkc"
-          git config --global user.email "$GIT_EMAIL"
-          git add sep.json release_notes.txt
-          new_version=$(cat version.txt)
-          git commit -m "Update sep.json and release_notes.txt to version $new_version" || { echo "No changes to commit"; exit 0; }
-          echo "Token: $PAT_TOKEN"
-          echo "Email: $GIT_EMAIL"
-          git push https://x-access-token:$PAT_TOKEN@github.com/androkc/joint.git || { echo "Git push failed"; exit 1; }
-
+         git config --global user.name "androkc"
+         git config --global user.email "$GIT_EMAIL"
+         git add sep.json release_notes.txt
+         new_version=$(cat version.txt)
+         git commit -m "Update sep.json and release_notes.txt to version $new_version" || { echo "No changes to commit"; exit 0; }
+         echo "Email: $GIT_EMAIL"
+         git push origin || { echo "Git push failed"; exit 1; }
 
 
 
